# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toolbox.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ToolBoxDialog(object):
    def setupUi(self, ToolBoxDialog):
        ToolBoxDialog.setObjectName(_fromUtf8("ToolBoxDialog"))
        ToolBoxDialog.resize(800, 600)
        self.horizontalLayout = QtGui.QHBoxLayout(ToolBoxDialog)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(ToolBoxDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.filefilter = FileFilterQt(self.tab_3)
        self.filefilter.setMinimumSize(QtCore.QSize(428, 522))
        self.filefilter.setObjectName(_fromUtf8("filefilter"))
        self.horizontalLayout_4.addWidget(self.filefilter)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.tab_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.editDstDir = DropEdit(self.tab_3)
        self.editDstDir.setObjectName(_fromUtf8("editDstDir"))
        self.horizontalLayout_2.addWidget(self.editDstDir)
        self.btnDstDir = QtGui.QPushButton(self.tab_3)
        self.btnDstDir.setObjectName(_fromUtf8("btnDstDir"))
        self.horizontalLayout_2.addWidget(self.btnDstDir)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBox = QtGui.QGroupBox(self.tab_3)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.comboFail = QtGui.QComboBox(self.groupBox)
        self.comboFail.setObjectName(_fromUtf8("comboFail"))
        self.comboFail.addItem(_fromUtf8(""))
        self.comboFail.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboFail, 0, 1, 1, 1)
        self.comboUnhit = QtGui.QComboBox(self.groupBox)
        self.comboUnhit.setObjectName(_fromUtf8("comboUnhit"))
        self.comboUnhit.addItem(_fromUtf8(""))
        self.comboUnhit.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboUnhit, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.comboExclude = QtGui.QComboBox(self.groupBox)
        self.comboExclude.setObjectName(_fromUtf8("comboExclude"))
        self.comboExclude.addItem(_fromUtf8(""))
        self.comboExclude.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboExclude, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.btnAction_DirEncode = QtGui.QPushButton(self.tab_5)
        self.btnAction_DirEncode.setObjectName(_fromUtf8("btnAction_DirEncode"))
        self.gridLayout_2.addWidget(self.btnAction_DirEncode, 4, 0, 1, 2)
        self.comboEncode_DirEncode = QtGui.QComboBox(self.tab_5)
        self.comboEncode_DirEncode.setObjectName(_fromUtf8("comboEncode_DirEncode"))
        self.gridLayout_2.addWidget(self.comboEncode_DirEncode, 0, 1, 2, 1)
        self.comboNewline_DirEncode = QtGui.QComboBox(self.tab_5)
        self.comboNewline_DirEncode.setObjectName(_fromUtf8("comboNewline_DirEncode"))
        self.gridLayout_2.addWidget(self.comboNewline_DirEncode, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab_5)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 2, 1)
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnAction_DirKatakana = QtGui.QPushButton(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAction_DirKatakana.sizePolicy().hasHeightForWidth())
        self.btnAction_DirKatakana.setSizePolicy(sizePolicy)
        self.btnAction_DirKatakana.setObjectName(_fromUtf8("btnAction_DirKatakana"))
        self.horizontalLayout_3.addWidget(self.btnAction_DirKatakana)
        self.tabWidget_2.addTab(self.tab_6, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget_2)
        self.listWidget = QtGui.QListWidget(self.tab_3)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        self.label.setBuddy(self.editDstDir)
        self.label_2.setBuddy(self.comboFail)
        self.label_3.setBuddy(self.comboUnhit)
        self.label_4.setBuddy(self.comboExclude)
        self.label_6.setBuddy(self.comboNewline_DirEncode)
        self.label_5.setBuddy(self.comboEncode_DirEncode)

        self.retranslateUi(ToolBoxDialog)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QObject.connect(self.btnDstDir, QtCore.SIGNAL(_fromUtf8("clicked()")), ToolBoxDialog.onBtnDstDir)
        QtCore.QObject.connect(self.btnAction_DirEncode, QtCore.SIGNAL(_fromUtf8("clicked()")), ToolBoxDialog.onBtnActionDirEncode)
        QtCore.QObject.connect(self.btnAction_DirKatakana, QtCore.SIGNAL(_fromUtf8("clicked()")), ToolBoxDialog.onBtnActionDirKatakana)
        QtCore.QMetaObject.connectSlotsByName(ToolBoxDialog)

    def retranslateUi(self, ToolBoxDialog):
        ToolBoxDialog.setWindowTitle(_translate("ToolBoxDialog", "ToolBox", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ToolBoxDialog", "Text", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ToolBoxDialog", "File", None))
        self.label.setText(_translate("ToolBoxDialog", "Dest Dir", None))
        self.btnDstDir.setText(_translate("ToolBoxDialog", "...", None))
        self.groupBox.setTitle(_translate("ToolBoxDialog", "Exception Action", None))
        self.label_2.setText(_translate("ToolBoxDialog", "Fail Files", None))
        self.comboFail.setItemText(0, _translate("ToolBoxDialog", "Ignore", None))
        self.comboFail.setItemText(1, _translate("ToolBoxDialog", "Copy", None))
        self.comboUnhit.setItemText(0, _translate("ToolBoxDialog", "Ignore", None))
        self.comboUnhit.setItemText(1, _translate("ToolBoxDialog", "Copy", None))
        self.label_3.setText(_translate("ToolBoxDialog", "UnHit Files", None))
        self.label_4.setText(_translate("ToolBoxDialog", "Excluded Files", None))
        self.comboExclude.setItemText(0, _translate("ToolBoxDialog", "Ignore", None))
        self.comboExclude.setItemText(1, _translate("ToolBoxDialog", "Copy", None))
        self.btnAction_DirEncode.setText(_translate("ToolBoxDialog", "Action", None))
        self.label_6.setText(_translate("ToolBoxDialog", "Output Newline", None))
        self.label_5.setText(_translate("ToolBoxDialog", "Output Encode", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("ToolBoxDialog", "Encode", None))
        self.btnAction_DirKatakana.setText(_translate("ToolBoxDialog", "Action", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("ToolBoxDialog", "Katakana", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("ToolBoxDialog", "Folder", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("ToolBoxDialog", "Source", None))

from dropedit import DropEdit
from filefilterqt import FileFilterQt
