# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toolbox.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ToolBoxDialog(object):
    def setupUi(self, ToolBoxDialog):
        ToolBoxDialog.setObjectName(_fromUtf8("ToolBoxDialog"))
        ToolBoxDialog.resize(800, 600)
        self.horizontalLayout = QtGui.QHBoxLayout(ToolBoxDialog)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(ToolBoxDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.filefilter = FileFilterQt(self.tab_3)
        self.filefilter.setMinimumSize(QtCore.QSize(428, 522))
        self.filefilter.setObjectName(_fromUtf8("filefilter"))
        self.horizontalLayout_4.addWidget(self.filefilter)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.tab_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.editDstDir = DropEdit(self.tab_3)
        self.editDstDir.setObjectName(_fromUtf8("editDstDir"))
        self.horizontalLayout_2.addWidget(self.editDstDir)
        self.btnDstDir = QtGui.QPushButton(self.tab_3)
        self.btnDstDir.setObjectName(_fromUtf8("btnDstDir"))
        self.horizontalLayout_2.addWidget(self.btnDstDir)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBox = QtGui.QGroupBox(self.tab_3)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.comboFail = QtGui.QComboBox(self.groupBox)
        self.comboFail.setObjectName(_fromUtf8("comboFail"))
        self.comboFail.addItem(_fromUtf8(""))
        self.comboFail.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboFail, 0, 1, 1, 1)
        self.comboUnhit = QtGui.QComboBox(self.groupBox)
        self.comboUnhit.setObjectName(_fromUtf8("comboUnhit"))
        self.comboUnhit.addItem(_fromUtf8(""))
        self.comboUnhit.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboUnhit, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.comboExclude = QtGui.QComboBox(self.groupBox)
        self.comboExclude.setObjectName(_fromUtf8("comboExclude"))
        self.comboExclude.addItem(_fromUtf8(""))
        self.comboExclude.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboExclude, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.tabWidget_2 = QtGui.QTabWidget(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.btnAction_DirEncode = QtGui.QPushButton(self.tab_5)
        self.btnAction_DirEncode.setObjectName(_fromUtf8("btnAction_DirEncode"))
        self.gridLayout_2.addWidget(self.btnAction_DirEncode, 4, 0, 1, 2)
        self.comboEncode_DirEncode = QtGui.QComboBox(self.tab_5)
        self.comboEncode_DirEncode.setObjectName(_fromUtf8("comboEncode_DirEncode"))
        self.gridLayout_2.addWidget(self.comboEncode_DirEncode, 0, 1, 2, 1)
        self.comboNewline_DirEncode = QtGui.QComboBox(self.tab_5)
        self.comboNewline_DirEncode.setObjectName(_fromUtf8("comboNewline_DirEncode"))
        self.gridLayout_2.addWidget(self.comboNewline_DirEncode, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab_5)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 2, 1)
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnAction_DirKatakana = QtGui.QPushButton(self.tab_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAction_DirKatakana.sizePolicy().hasHeightForWidth())
        self.btnAction_DirKatakana.setSizePolicy(sizePolicy)
        self.btnAction_DirKatakana.setObjectName(_fromUtf8("btnAction_DirKatakana"))
        self.horizontalLayout_3.addWidget(self.btnAction_DirKatakana)
        self.tabWidget_2.addTab(self.tab_6, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget_2)
        self.listWidget = QtGui.QListWidget(self.tab_3)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btnExtractFunc = QtGui.QPushButton(self.tab_4)
        self.btnExtractFunc.setObjectName(_fromUtf8("btnExtractFunc"))
        self.horizontalLayout_5.addWidget(self.btnExtractFunc)
        self.btnExtractFuncDiff = QtGui.QPushButton(self.tab_4)
        self.btnExtractFuncDiff.setObjectName(_fromUtf8("btnExtractFuncDiff"))
        self.horizontalLayout_5.addWidget(self.btnExtractFuncDiff)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 4, 0, 1, 3)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.checkLines = QtGui.QCheckBox(self.groupBox_2)
        self.checkLines.setChecked(True)
        self.checkLines.setObjectName(_fromUtf8("checkLines"))
        self.gridLayout_3.addWidget(self.checkLines, 3, 0, 1, 1)
        self.checkStartline = QtGui.QCheckBox(self.groupBox_2)
        self.checkStartline.setObjectName(_fromUtf8("checkStartline"))
        self.gridLayout_3.addWidget(self.checkStartline, 0, 1, 1, 1)
        self.checkFuncName = QtGui.QCheckBox(self.groupBox_2)
        self.checkFuncName.setChecked(True)
        self.checkFuncName.setObjectName(_fromUtf8("checkFuncName"))
        self.gridLayout_3.addWidget(self.checkFuncName, 3, 2, 1, 1)
        self.checkFuncID = QtGui.QCheckBox(self.groupBox_2)
        self.checkFuncID.setChecked(True)
        self.checkFuncID.setObjectName(_fromUtf8("checkFuncID"))
        self.gridLayout_3.addWidget(self.checkFuncID, 3, 1, 1, 1)
        self.checkStopline = QtGui.QCheckBox(self.groupBox_2)
        self.checkStopline.setObjectName(_fromUtf8("checkStopline"))
        self.gridLayout_3.addWidget(self.checkStopline, 0, 2, 1, 1)
        self.checkFilePath = QtGui.QCheckBox(self.groupBox_2)
        self.checkFilePath.setChecked(True)
        self.checkFilePath.setObjectName(_fromUtf8("checkFilePath"))
        self.gridLayout_3.addWidget(self.checkFilePath, 0, 0, 1, 1)
        self.line = QtGui.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_3.addWidget(self.line, 2, 0, 1, 4)
        self.checkCondition = QtGui.QCheckBox(self.groupBox_2)
        self.checkCondition.setObjectName(_fromUtf8("checkCondition"))
        self.gridLayout_3.addWidget(self.checkCondition, 1, 1, 1, 1)
        self.checkLoop = QtGui.QCheckBox(self.groupBox_2)
        self.checkLoop.setObjectName(_fromUtf8("checkLoop"))
        self.gridLayout_3.addWidget(self.checkLoop, 1, 2, 1, 1)
        self.checkSubFuncCount = QtGui.QCheckBox(self.groupBox_2)
        self.checkSubFuncCount.setChecked(False)
        self.checkSubFuncCount.setObjectName(_fromUtf8("checkSubFuncCount"))
        self.gridLayout_3.addWidget(self.checkSubFuncCount, 0, 3, 1, 1)
        self.checkSubFuncName = QtGui.QCheckBox(self.groupBox_2)
        self.checkSubFuncName.setChecked(False)
        self.checkSubFuncName.setObjectName(_fromUtf8("checkSubFuncName"))
        self.gridLayout_3.addWidget(self.checkSubFuncName, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 2, 0, 1, 3)
        self.btnBaseSource = QtGui.QPushButton(self.tab_4)
        self.btnBaseSource.setObjectName(_fromUtf8("btnBaseSource"))
        self.gridLayout_4.addWidget(self.btnBaseSource, 1, 2, 1, 1)
        self.editBaseSource = DropEdit(self.tab_4)
        self.editBaseSource.setObjectName(_fromUtf8("editBaseSource"))
        self.gridLayout_4.addWidget(self.editBaseSource, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        self.btnNewSource = QtGui.QPushButton(self.tab_4)
        self.btnNewSource.setObjectName(_fromUtf8("btnNewSource"))
        self.gridLayout_4.addWidget(self.btnNewSource, 0, 2, 1, 1)
        self.editNewSource = DropEdit(self.tab_4)
        self.editNewSource.setObjectName(_fromUtf8("editNewSource"))
        self.gridLayout_4.addWidget(self.editNewSource, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.listWidget_Source = QtGui.QListWidget(self.tab_4)
        self.listWidget_Source.setObjectName(_fromUtf8("listWidget_Source"))
        self.gridLayout_4.addWidget(self.listWidget_Source, 3, 0, 1, 3)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        self.label.setBuddy(self.editDstDir)
        self.label_2.setBuddy(self.comboFail)
        self.label_3.setBuddy(self.comboUnhit)
        self.label_4.setBuddy(self.comboExclude)
        self.label_6.setBuddy(self.comboNewline_DirEncode)
        self.label_5.setBuddy(self.comboEncode_DirEncode)
        self.label_8.setBuddy(self.editBaseSource)
        self.label_7.setBuddy(self.editNewSource)

        self.retranslateUi(ToolBoxDialog)
        self.tabWidget.setCurrentIndex(3)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QObject.connect(self.btnDstDir, QtCore.SIGNAL(_fromUtf8("clicked()")), ToolBoxDialog.onBtnDstDir)
        QtCore.QObject.connect(self.btnAction_DirEncode, QtCore.SIGNAL(_fromUtf8("clicked()")), ToolBoxDialog.onBtnActionDirEncode)
        QtCore.QObject.connect(self.btnAction_DirKatakana, QtCore.SIGNAL(_fromUtf8("clicked()")), ToolBoxDialog.onBtnActionDirKatakana)
        QtCore.QObject.connect(self.btnNewSource, QtCore.SIGNAL(_fromUtf8("clicked()")), ToolBoxDialog.onBtnNewSource)
        QtCore.QObject.connect(self.btnBaseSource, QtCore.SIGNAL(_fromUtf8("clicked()")), ToolBoxDialog.onBtnBaseSource)
        QtCore.QObject.connect(self.btnExtractFunc, QtCore.SIGNAL(_fromUtf8("clicked()")), ToolBoxDialog.onBtnExtractFunc)
        QtCore.QObject.connect(self.btnExtractFuncDiff, QtCore.SIGNAL(_fromUtf8("clicked()")), ToolBoxDialog.onBtnExtractFuncDiff)
        QtCore.QMetaObject.connectSlotsByName(ToolBoxDialog)

    def retranslateUi(self, ToolBoxDialog):
        ToolBoxDialog.setWindowTitle(_translate("ToolBoxDialog", "ToolBox", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ToolBoxDialog", "Text", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ToolBoxDialog", "File", None))
        self.label.setText(_translate("ToolBoxDialog", "Dest Dir", None))
        self.btnDstDir.setText(_translate("ToolBoxDialog", "...", None))
        self.groupBox.setTitle(_translate("ToolBoxDialog", "Exception Action", None))
        self.label_2.setText(_translate("ToolBoxDialog", "Fail Files", None))
        self.comboFail.setItemText(0, _translate("ToolBoxDialog", "Ignore", None))
        self.comboFail.setItemText(1, _translate("ToolBoxDialog", "Copy", None))
        self.comboUnhit.setItemText(0, _translate("ToolBoxDialog", "Ignore", None))
        self.comboUnhit.setItemText(1, _translate("ToolBoxDialog", "Copy", None))
        self.label_3.setText(_translate("ToolBoxDialog", "UnHit Files", None))
        self.label_4.setText(_translate("ToolBoxDialog", "Excluded Files", None))
        self.comboExclude.setItemText(0, _translate("ToolBoxDialog", "Ignore", None))
        self.comboExclude.setItemText(1, _translate("ToolBoxDialog", "Copy", None))
        self.btnAction_DirEncode.setText(_translate("ToolBoxDialog", "Action", None))
        self.label_6.setText(_translate("ToolBoxDialog", "Output Newline", None))
        self.label_5.setText(_translate("ToolBoxDialog", "Output Encode", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("ToolBoxDialog", "Encode", None))
        self.btnAction_DirKatakana.setText(_translate("ToolBoxDialog", "Action", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("ToolBoxDialog", "Katakana", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("ToolBoxDialog", "Folder", None))
        self.btnExtractFunc.setText(_translate("ToolBoxDialog", "Extract", None))
        self.btnExtractFuncDiff.setText(_translate("ToolBoxDialog", "Extract Diff", None))
        self.groupBox_2.setTitle(_translate("ToolBoxDialog", "Output Field", None))
        self.checkLines.setText(_translate("ToolBoxDialog", "Lines", None))
        self.checkStartline.setText(_translate("ToolBoxDialog", "Start Line", None))
        self.checkFuncName.setText(_translate("ToolBoxDialog", "Function Name", None))
        self.checkFuncID.setText(_translate("ToolBoxDialog", "Function ID", None))
        self.checkStopline.setText(_translate("ToolBoxDialog", "Stop Line", None))
        self.checkFilePath.setText(_translate("ToolBoxDialog", "File Path", None))
        self.checkCondition.setText(_translate("ToolBoxDialog", "Condition", None))
        self.checkLoop.setText(_translate("ToolBoxDialog", "Loop", None))
        self.checkSubFuncCount.setText(_translate("ToolBoxDialog", "Sub Function Call Count", None))
        self.checkSubFuncName.setText(_translate("ToolBoxDialog", "Sub Function Names", None))
        self.btnBaseSource.setText(_translate("ToolBoxDialog", "...", None))
        self.label_8.setText(_translate("ToolBoxDialog", "Base Source Dir", None))
        self.btnNewSource.setText(_translate("ToolBoxDialog", "...", None))
        self.label_7.setText(_translate("ToolBoxDialog", "New Source Dir", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("ToolBoxDialog", "Source", None))

from dropedit import DropEdit
from filefilterqt import FileFilterQt
