# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'encodechanger.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EncodeChangerDialog(object):
    def setupUi(self, EncodeChangerDialog):
        EncodeChangerDialog.setObjectName(_fromUtf8("EncodeChangerDialog"))
        EncodeChangerDialog.resize(600, 450)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/ec.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        EncodeChangerDialog.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(EncodeChangerDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(EncodeChangerDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.editSrcDir = DropEdit(EncodeChangerDialog)
        self.editSrcDir.setObjectName(_fromUtf8("editSrcDir"))
        self.gridLayout.addWidget(self.editSrcDir, 0, 1, 1, 1)
        self.btnSrcDir = QtGui.QPushButton(EncodeChangerDialog)
        self.btnSrcDir.setObjectName(_fromUtf8("btnSrcDir"))
        self.gridLayout.addWidget(self.btnSrcDir, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(EncodeChangerDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.editDstDir = DropEdit(EncodeChangerDialog)
        self.editDstDir.setObjectName(_fromUtf8("editDstDir"))
        self.gridLayout.addWidget(self.editDstDir, 1, 1, 1, 1)
        self.btnDstDir = QtGui.QPushButton(EncodeChangerDialog)
        self.btnDstDir.setObjectName(_fromUtf8("btnDstDir"))
        self.gridLayout.addWidget(self.btnDstDir, 1, 2, 1, 1)
        self.label_4 = QtGui.QLabel(EncodeChangerDialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtGui.QLabel(EncodeChangerDialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_3 = QtGui.QLabel(EncodeChangerDialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.comboEncode = QtGui.QComboBox(EncodeChangerDialog)
        self.comboEncode.setObjectName(_fromUtf8("comboEncode"))
        self.gridLayout.addWidget(self.comboEncode, 4, 1, 1, 1)
        self.checkCopyOther = QtGui.QCheckBox(EncodeChangerDialog)
        self.checkCopyOther.setObjectName(_fromUtf8("checkCopyOther"))
        self.gridLayout.addWidget(self.checkCopyOther, 4, 2, 1, 1)
        self.label_6 = QtGui.QLabel(EncodeChangerDialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.comboNewline = QtGui.QComboBox(EncodeChangerDialog)
        self.comboNewline.setObjectName(_fromUtf8("comboNewline"))
        self.comboNewline.addItem(_fromUtf8(""))
        self.comboNewline.addItem(_fromUtf8(""))
        self.comboNewline.addItem(_fromUtf8(""))
        self.comboNewline.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboNewline, 5, 1, 1, 1)
        self.checkIgnoreVCS = QtGui.QCheckBox(EncodeChangerDialog)
        self.checkIgnoreVCS.setChecked(True)
        self.checkIgnoreVCS.setObjectName(_fromUtf8("checkIgnoreVCS"))
        self.gridLayout.addWidget(self.checkIgnoreVCS, 5, 2, 1, 1)
        self.tabWidget = QtGui.QTabWidget(EncodeChangerDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.listAll = QtGui.QListWidget(self.tab)
        self.listAll.setObjectName(_fromUtf8("listAll"))
        self.horizontalLayout.addWidget(self.listAll)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.listHit = QtGui.QListWidget(self.tab_2)
        self.listHit.setObjectName(_fromUtf8("listHit"))
        self.horizontalLayout_2.addWidget(self.listHit)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.listOther = QtGui.QListWidget(self.tab_3)
        self.listOther.setObjectName(_fromUtf8("listOther"))
        self.horizontalLayout_3.addWidget(self.listOther)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.listLog = QtGui.QListWidget(self.tab_4)
        self.listLog.setObjectName(_fromUtf8("listLog"))
        self.horizontalLayout_4.addWidget(self.listLog)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 7, 0, 1, 3)
        self.comboRegex = QtGui.QComboBox(EncodeChangerDialog)
        self.comboRegex.setObjectName(_fromUtf8("comboRegex"))
        self.comboRegex.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboRegex, 2, 1, 1, 2)
        self.editRegex = QtGui.QLineEdit(EncodeChangerDialog)
        self.editRegex.setObjectName(_fromUtf8("editRegex"))
        self.gridLayout.addWidget(self.editRegex, 3, 1, 1, 2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btnPreview = QtGui.QPushButton(EncodeChangerDialog)
        self.btnPreview.setObjectName(_fromUtf8("btnPreview"))
        self.horizontalLayout_5.addWidget(self.btnPreview)
        self.btnAction = QtGui.QPushButton(EncodeChangerDialog)
        self.btnAction.setObjectName(_fromUtf8("btnAction"))
        self.horizontalLayout_5.addWidget(self.btnAction)
        self.gridLayout.addLayout(self.horizontalLayout_5, 6, 0, 1, 3)
        self.label.setBuddy(self.editSrcDir)
        self.label_2.setBuddy(self.editDstDir)
        self.label_4.setBuddy(self.comboRegex)
        self.label_5.setBuddy(self.editRegex)
        self.label_3.setBuddy(self.comboEncode)
        self.label_6.setBuddy(self.comboNewline)

        self.retranslateUi(EncodeChangerDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.btnSrcDir, QtCore.SIGNAL(_fromUtf8("clicked()")), EncodeChangerDialog.onBtnSrcDir)
        QtCore.QObject.connect(self.btnDstDir, QtCore.SIGNAL(_fromUtf8("clicked()")), EncodeChangerDialog.onBtnDstDir)
        QtCore.QObject.connect(self.btnPreview, QtCore.SIGNAL(_fromUtf8("clicked()")), EncodeChangerDialog.onBtnPreview)
        QtCore.QObject.connect(self.btnAction, QtCore.SIGNAL(_fromUtf8("clicked()")), EncodeChangerDialog.onBtnAction)
        QtCore.QObject.connect(self.comboRegex, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), EncodeChangerDialog.onComboRegex)
        QtCore.QObject.connect(self.editRegex, QtCore.SIGNAL(_fromUtf8("textEdited(QString)")), EncodeChangerDialog.onEditRegex)
        QtCore.QMetaObject.connectSlotsByName(EncodeChangerDialog)
        EncodeChangerDialog.setTabOrder(self.editSrcDir, self.btnSrcDir)
        EncodeChangerDialog.setTabOrder(self.btnSrcDir, self.editDstDir)
        EncodeChangerDialog.setTabOrder(self.editDstDir, self.btnDstDir)
        EncodeChangerDialog.setTabOrder(self.btnDstDir, self.comboRegex)
        EncodeChangerDialog.setTabOrder(self.comboRegex, self.editRegex)
        EncodeChangerDialog.setTabOrder(self.editRegex, self.comboEncode)
        EncodeChangerDialog.setTabOrder(self.comboEncode, self.comboNewline)
        EncodeChangerDialog.setTabOrder(self.comboNewline, self.btnAction)
        EncodeChangerDialog.setTabOrder(self.btnAction, self.tabWidget)
        EncodeChangerDialog.setTabOrder(self.tabWidget, self.listAll)
        EncodeChangerDialog.setTabOrder(self.listAll, self.listHit)
        EncodeChangerDialog.setTabOrder(self.listHit, self.listOther)
        EncodeChangerDialog.setTabOrder(self.listOther, self.listLog)

    def retranslateUi(self, EncodeChangerDialog):
        EncodeChangerDialog.setWindowTitle(_translate("EncodeChangerDialog", "EncodeChanger", None))
        self.label.setText(_translate("EncodeChangerDialog", "Source Dir", None))
        self.btnSrcDir.setText(_translate("EncodeChangerDialog", "...", None))
        self.label_2.setText(_translate("EncodeChangerDialog", "Destination Dir", None))
        self.btnDstDir.setText(_translate("EncodeChangerDialog", "...", None))
        self.label_4.setText(_translate("EncodeChangerDialog", "Files Filter", None))
        self.label_5.setText(_translate("EncodeChangerDialog", "Filter RegEx", None))
        self.label_3.setText(_translate("EncodeChangerDialog", "Output Encode", None))
        self.checkCopyOther.setText(_translate("EncodeChangerDialog", "Copy Other Files", None))
        self.label_6.setText(_translate("EncodeChangerDialog", "Output Newline", None))
        self.comboNewline.setItemText(0, _translate("EncodeChangerDialog", "System", None))
        self.comboNewline.setItemText(1, _translate("EncodeChangerDialog", "Dos", None))
        self.comboNewline.setItemText(2, _translate("EncodeChangerDialog", "Unix", None))
        self.comboNewline.setItemText(3, _translate("EncodeChangerDialog", "Mac", None))
        self.checkIgnoreVCS.setText(_translate("EncodeChangerDialog", "Ignore VCS Files", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("EncodeChangerDialog", "All Files", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("EncodeChangerDialog", "Hit Files", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("EncodeChangerDialog", "Other Files", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("EncodeChangerDialog", "Error Logs", None))
        self.comboRegex.setItemText(0, _translate("EncodeChangerDialog", "Manual", None))
        self.btnPreview.setText(_translate("EncodeChangerDialog", "Preview", None))
        self.btnAction.setText(_translate("EncodeChangerDialog", "Action", None))

from dropedit import DropEdit
import encodechanger_rc
